name: Auto Merge Owner PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies and run linters
      run: |
        pip install -r requirements.txt 
        flake8 --ignore=E501,E231 *.py tests/*.py 
        pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py

    - name: Run unit tests
      run: python -m unittest --verbose --failfast

  merge:
    if: github.actor == 'kennedy-u' || github.actor == 'octocat'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: hmarr/auto-approve-action@v4
      with:
        github-token: ${{ secrets.MY_PAT }}

    - uses: managedkaos/merge-pull-request@v2.2
      env:
        MY_PAT: ${{ secrets.MY_PAT }}
        

        