name: Auto Merge Owner PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies and run linters
      run: |
        pip install -r requirements.txt
        flake8 --ignore=E501,E231 *.py
        pylint --errors-only --disable=C0301 --disable=C0326 *.py

    - name: Run unit tests
      run: python -m unittest --verbose --failfast

  merge:
    if: github.actor == 'kennedy-u' || github.actor == 'octocat'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.MY_PAT }}

    - uses: managedkaos/merge-pull-request@v1.2
      with:
        github_token: ${{ secrets.MY_PAT }}
